// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { PostApiV1SongsData, GetApiV1PlaygroundData, PostApiV1AuthLoginData, GetApiV1DocsData, GetApiV1DocsJsonData } from './types.gen';

export const client = createClient(createConfig());

export class DefaultService {
    public static postApiV1Songs<ThrowOnError extends boolean = false>(options: Options<PostApiV1SongsData, ThrowOnError>) {
        return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
            url: '/api/v1/songs/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getApiV1Playground<ThrowOnError extends boolean = false>(options?: Options<GetApiV1PlaygroundData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
            url: '/api/v1/playground/',
            ...options
        });
    }
    
    public static postApiV1AuthLogin<ThrowOnError extends boolean = false>(options: Options<PostApiV1AuthLoginData, ThrowOnError>) {
        return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
            url: '/api/v1/auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getApiV1Docs<ThrowOnError extends boolean = false>(options?: Options<GetApiV1DocsData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
            url: '/api/v1/docs',
            ...options
        });
    }
    
    public static getApiV1DocsJson<ThrowOnError extends boolean = false>(options?: Options<GetApiV1DocsJsonData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
            url: '/api/v1/docs/json',
            ...options
        });
    }
    
}